let currencies = {
    "USD - US Dollar" : "US",
    "EUR - Euro" : "FR",
    "GBP - British Pound" : "GB",
    "CAD - Canadian Dollar" : "CA",
    "AUD - Australian Dollar" : "AU",
    "JPY - Japanese Yen" : "JP",
    "INR - Indian Rupee" : "IN",
    "NZD - New Zealand Dollar" : "NZ",
    "CHF - Swiss Franc" : "CH",
    "ZAR - South African Rand" : "ZA",
    "RUB - Russian Ruble" : "RU",
    "BGN - Bulgarian Lev" : "BG",
    "SGD - Singapore Dollar" : "SG",
    "HKD - Hong Kong Dollar" : "HK",
    "SEK - Swedish Krona" : "SE",
    "THB - Thai Baht" : "TH",
    "HUF - Hungarian Forint" : "HU",
    "CNY - Chinese Yuan Renminbi" : "CN",
    "NOK - Norwegian Krone" : "BV",
    "MXN - Mexican Peso" : "MX",
    "DKK - Danish Krone" : "DK",
    "MYR - Malaysian Ringgit" : "MY",
    "PLN - Polish Zloty" : "PL",
    "BRL - Brazilian Real" : "BR",
    "PHP - Philippine Peso" : "PH",
    "IDR - Indonesian Rupiah" : "ID",
    "CZK - Czech Koruna" : "CZ",
    "AED - Emirati Dirham" : "AE",
    "TWD - Taiwan New Dollar" : "TW",
    "KRW - South Korean Won" : "KR",
    "ILS - Israeli Shekel" : "IL",
    "ARS - Argentine Peso" : "AR",
    "CLP - Chilean Peso" : "CL",
    "EGP - Egyptian Pound" : "EG",
    "TRY - Turkish Lira" : "TR",
    "RON - Romanian Leu" : "RO",
    "SAR - Saudi Arabian Riyal" : "SA",
    "PKR - Pakistani Rupee" : "PK",
    "COP - Colombian Peso" : "CO",
    "IQD - Iraqi Dinar" : "IQ",
    "FJD - Fijian Dollar" : "FJ",
    "KWD - Kuwaiti Dinar" : "KW",
    "BAM - Bosnian Convertible Mark" : "BA",
    "ISK - Icelandic Krona" : "IS",
    "MAD - Moroccan Dirham" : "MA",
    "VND - Vietnamese Dong" : "VN",
    "JMD - Jamaican Dollar" : "JM",
    "JOD - Jordanian Dinar" : "JO",
    "DOP - Dominican Peso" : "DO",
    "PEN - Peruvian Sol" : "PE",
    "CRC - Costa Rican Colon" : "CR",
    "BHD - Bahraini Dinar" : "BH",
    "BDT - Bangladeshi Taka" : "BD",
    "DZD - Algerian Dinar" : "DZ",
    "KES - Kenyan Shilling" : "KE",
    "LKR - Sri Lankan Rupee" : "LK",
    "OMR - Omani Rial" : "OM",
    "QAR - Qatari Riyal" : "QA",
    "XOF - CFA Franc" : "BE",
    "IRR - Iranian Rial" : "IR",
    "XCD - East Caribbean Dollar" : "AG",
    "TND - Tunisian Dinar" : "TN",
    "TTD - Trinidadian Dollar" : "TT",
    "XPF - CFP Franc" : "NC",
    "ZMW - Zambian Kwacha" : "ZM",
    "BBD - Barbadian or Bajan Dollar" : "BB",
    "NGN - Nigerian Naira" : "NG",
    "LBP - Lebanese Pound" : "LB",
    "XAF - Central African CFA Franc BEAC" : "CF",
    "MUR - Mauritian Rupee" : "MU",
    "BSD - Bahamian Dollar" : "BS",
    "ALL - Albanian Lek" : "AL",
    "UYU - Uruguayan Peso" : "UY",
    "BMD - Bermudian Dollar" : "BM",
    "UAH - Ukrainian Hryvnia" : "UA",
    "GTQ - Guatemalan Quetzal" : "GT",
    "BWP - Botswana Pula" : "BW",
    "BOB - Bolivian Bolíviano" : "BO",
    "CUP - Cuban Peso" : "CU",
    "PYG - Paraguayan Guarani" : "PY",
    "HNL - Honduran Lempira" : "HN",
    "ZWL - Zimbabwean Dollar" : "ZW",
    "NIO - Nicaraguan Cordoba" : "NI",
    "RSD - Serbian Dinar" : "RS",
    "NPR - Nepalese Rupee" : "NP",
    "HTG - Haitian Gourde" : "HT",
    "PAB - Panamanian Balboa" : "PA",
    "GYD - Guyanese Dollar" : "GY",
    "KYD - Caymanian Dollar" : "KY",
    "TZS - Tanzanian Shilling" : "TZ",
    "CVE - Cape Verdean Escudo" : "CV",
    "FKP - Falkland Island Pound" : "FK",
    "ANG - Dutch Guilder" : "xx",
    "UGX - Ugandan Shilling" : "UG",
    "MGA - Malagasy Ariary" : "MG",
    "GEL - Georgian Lari" : "GE",
    "ETB - Ethiopian Birr" : "ET",
    "MDL - Moldovan Leu" : "MD",
    "VUV - Ni-Vanuatu Vatu" : "VU",
    "SYP - Syrian Pound" : "SY",
    "BND - Bruneian Dollar" : "BN",
    "KHR - Cambodian Riel" : "KH",
    "NAD - Namibian Dollar" : "NA",
    "MKD - Macedonian Denar" : "MK",
    "AOA - Angolan Kwanza" : "AO",
    "PGK - Papua New Guinean Kina" : "PG",
    "MMK - Burmese Kyat" : "MM",
    "KZT - Kazakhstani Tenge" : "KZ",
    "MOP - Macau Pataca" : "MO",
    "MZN - Mozambican Metical" : "MZ",
    "LYD - Libyan Dinar" : "LY",
    "SLL - Sierra Leonean Leone" : "SL",
    "GNF - Guinean Franc" : "GN",
    "BYN - Belarusian Ruble" : "BY",
    "GMD - Gambian Dalasi" : "GM",
    "AMD - Armenian Dram" : "AM",
    "YER - Yemeni Rial" : "YE",
    "LAK - Lao Kip" : "LA",
    "MWK - Malawian Kwacha" : "MW",
//  "KPW - North Korean Won" : "KP",
    "BIF - Burundian Franc" : "BI",
    "DJF - Djiboutian Franc" : "DJ",
    "MNT - Mongolian Tughrik" : "MN",
    "UZS - Uzbekistani Som" : "UZ",
    "TOP - Tongan Pa'anga" : "TO",
    "SCR - Seychellois Rupee" : "SC",
    "KGS - Kyrgyzstani Som" : "KG",
    "SBD - Solomon Islander Dollar" : "SB",
    "GIP - Gibraltar Pound" : "GI",
    "RWF - Rwandan Franc" : "RW",
    "CDF - Congolese Franc" : "CD",
    "MVR - Maldivian Rufiyaa" : "MV",
    "SOS - Somali Shilling" : "SO",
    "SZL - Swazi Lilangeni" : "SZ",
    "TJS - Tajikistani Somoni" : "TJ",
    "LRD - Liberian Dollar" : "LR",
    "LSL - Basotho Loti" : "LS",
    "KMF - Comorian Franc" : "KM",
    "TMT - Turkmenistani Manat" : "TM",
    "SRD - Surinamese Dollar" : "SR",
    "GGP - Guernsey Pound" : "GG",
    "AFN - Afghan Afghani" : "AF",
    "AZN - Azerbaijan Manat" : "AZ",
    "BZD - Belizean Dollar" : "BZ",
    "GHS - Ghanaian Cedi" : "GH",
    "SDG - Sudanese Pound" : "SD",
    "VES - Venezuelan Bolívar" : "VE"
}